/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : string,
  'contact' : DeliveryDetails,
  'orders' : Array<Order>,
}
export interface DeliveryDetails {
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'email' : string,
  'preferredDeliveryTime' : [] | [string],
  'address' : string,
  'phone' : string,
  'deliveryInstructions' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Offer {
  'id' : string,
  'title' : string,
  'endDate' : Time,
  'banner' : [] | [ExternalBlob],
  'description' : string,
  'isActive' : boolean,
  'startDate' : Time,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'deliveryDetails' : DeliveryDetails,
  'customer' : [] | [Principal],
  'deliveryTime' : Time,
  'orderTime' : Time,
  'products' : Array<Product>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'quantity' : bigint,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateOffer' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOffer' : ActorMethod<
    [string, string, [] | [ExternalBlob], Time, Time, boolean],
    string
  >,
  'createProduct' : ActorMethod<
    [string, string, bigint, bigint, boolean, [] | [ExternalBlob]],
    string
  >,
  'deactivateOffer' : ActorMethod<[string], undefined>,
  'deleteOffer' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getActiveOffers' : ActorMethod<[], Array<Offer>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllOffers' : ActorMethod<[], Array<Offer>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getProduct' : ActorMethod<[string], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'init' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [[] | [Principal], DeliveryDetails, Array<Product>],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOffer' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], Time, Time, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, bigint, boolean, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];